import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Check, Clock3, PackageCheck, Bike, ChefHat, RotateCcw } from 'lucide-react';
import { foodItems } from '../data/foods';

const KEY='foodexpress-orders';
const stages=['New','Confirmed','Preparing','Ready','Out for Delivery','Delivered'];
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function Orders(){
  const [orders,setOrders]=useState([]);const [selected,setSelected]=useState(null);const navigate=useNavigate();
  const refresh=useCallback(()=>{try{const customer=JSON.parse(localStorage.getItem(KEY)||'[]');const admin=JSON.parse(localStorage.getItem('fe-orders')||'[]');const joined=customer.map(o=>({...o,...(admin.find(a=>a.id===o.id)||{})}));setOrders(joined);const id=new URLSearchParams(window.location.search).get('orderId');setSelected(joined.find(o=>o.id===id)||null)}catch{setOrders([])}},[]);
  useEffect(()=>{refresh();window.addEventListener('business-data',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('business-data',refresh);window.removeEventListener('storage',refresh)}},[refresh]);
  const reorder=o=>{const cart=JSON.parse(localStorage.getItem('foodexpress-cart')||'[]');const next=[...cart];o.items.forEach(item=>{const food=foodItems.find(f=>f.id===item.id)||item;const match=next.find(x=>x.id===food.id);if(match)match.quantity+=item.quantity||1;else next.push({...food,quantity:item.quantity||1})});localStorage.setItem('foodexpress-cart',JSON.stringify(next));window.dispatchEvent(new Event('storage'));navigate('/cart')};
  const cancel=o=>{const updated=orders.map(x=>x.id===o.id?{...x,status:'Cancelled'}:x);localStorage.setItem(KEY,JSON.stringify(updated));const admin=JSON.parse(localStorage.getItem('fe-orders')||'[]').map(x=>x.id===o.id?{...x,status:'Cancelled'}:x);localStorage.setItem('fe-orders',JSON.stringify(admin));window.dispatchEvent(new Event('business-data'));refresh()};
  return <section className="container page-shell customer-orders"><div className="section-head"><div><span className="eyebrow small">Your timeline</span><h2>{selected?'Order tracking':'Your orders'}</h2><p>Every delicious moment, all in one place.</p></div></div>
  {selected&&<article className="tracking-card"><div className="tracking-head"><div><span className="order-confirmed"><Check size={15}/> Order confirmed</span><h3>{selected.id}</h3><p>{new Date(selected.date).toLocaleString()} · {selected.items?.length||0} items · {money(selected.total)}</p></div><span className="tracking-estimate"><Clock3 size={15}/> 30–40 min</span></div>{selected.status==='Cancelled'?<div className="tracking-cancelled">This order was cancelled.</div>:<div className="tracking-steps">{stages.map((stage,i)=>{const status=selected.status||'New';const active=Math.max(0,stages.indexOf(status));const done=i<=active;const current=i===active;const Icon=[Check,Check,ChefHat,PackageCheck,Bike,Check][i];return <div className={`tracking-step ${done?'done':''} ${current?'current':''}`} key={stage}><div className="tracking-node"><Icon size={16}/></div><span>{stage==='New'?'Confirmed':stage==='Preparing'?'Preparing':stage}</span></div>})}</div>}<div className="tracking-address"><b>Delivering to</b><span>{selected.address||'Address to be confirmed'}</span></div></article>}
  {orders.length?<div className="customer-order-list">{orders.map(o=><article className="customer-order-card" key={o.id}><div className="customer-order-top"><div><small>ORDER {o.id}</small><h3>{(o.items||[]).map(i=>i.name).join(', ')}</h3><span>{new Date(o.date).toLocaleDateString()} · {o.items?.reduce((n,x)=>n+(x.quantity||1),0)} items</span></div><div className="order-total"><b>{money(o.total)}</b><span className={`order-status ${String(o.status||'New').toLowerCase().replaceAll(' ','-')}`}>{o.status||'New'}</span></div></div><div className="customer-order-actions"><button onClick={()=>{setSelected(o);window.history.replaceState({},'',`/orders?orderId=${o.id}`);window.scrollTo({top:0,behavior:'smooth'})}}>Track order</button><button onClick={()=>reorder(o)}><RotateCcw size={14}/> Reorder</button>{!['Delivered','Cancelled','Out for Delivery'].includes(o.status)&&<button className="cancel-order" onClick={()=>cancel(o)}>Cancel order</button>}</div></article>)}</div>:<div className="empty-state"><h3>No orders yet.</h3><p>Choose a few favourites and your orders will show up here.</p><Link className="primary-btn" to="/menu">Browse the menu</Link></div>}</section>
}
